/* 
 * Equimpent rental API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using bondora.homeAssignment.ApiClient.Client;
using bondora.homeAssignment.Models.Contracts.Invoice;

namespace bondora.homeAssignment.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInvoiceApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>InvoiceContract</returns>
        InvoiceContract ApiInvoiceGetInvoiceGet ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of InvoiceContract</returns>
        ApiResponse<InvoiceContract> ApiInvoiceGetInvoiceGetWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void ApiInvoiceGetPrintedInvoiceGet ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiInvoiceGetPrintedInvoiceGetWithHttpInfo ();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInvoiceApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of InvoiceContract</returns>
        System.Threading.Tasks.Task<InvoiceContract> ApiInvoiceGetInvoiceGetAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (InvoiceContract)</returns>
        System.Threading.Tasks.Task<ApiResponse<InvoiceContract>> ApiInvoiceGetInvoiceGetAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiInvoiceGetPrintedInvoiceGetAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiInvoiceGetPrintedInvoiceGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInvoiceApi : IInvoiceApiSync, IInvoiceApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class InvoiceApi : IInvoiceApi
    {
        private bondora.homeAssignment.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public InvoiceApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public InvoiceApi(String basePath)
        {
            this.Configuration = bondora.homeAssignment.ApiClient.Client.Configuration.MergeConfigurations(
                bondora.homeAssignment.ApiClient.Client.GlobalConfiguration.Instance,
                new bondora.homeAssignment.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = bondora.homeAssignment.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public InvoiceApi(bondora.homeAssignment.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = bondora.homeAssignment.ApiClient.Client.Configuration.MergeConfigurations(
                bondora.homeAssignment.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = bondora.homeAssignment.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PetApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public InvoiceApi(bondora.homeAssignment.ApiClient.Client.ISynchronousClient client,bondora.homeAssignment.ApiClient.Client.IAsynchronousClient asyncClient, bondora.homeAssignment.ApiClient.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = bondora.homeAssignment.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public bondora.homeAssignment.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public bondora.homeAssignment.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public bondora.homeAssignment.ApiClient.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public bondora.homeAssignment.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>InvoiceContract</returns>
        public InvoiceContract ApiInvoiceGetInvoiceGet ()
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<InvoiceContract> localVarResponse = ApiInvoiceGetInvoiceGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of InvoiceContract</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse< InvoiceContract > ApiInvoiceGetInvoiceGetWithHttpInfo ()
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var response = this.Client.Get< InvoiceContract >("/api/Invoice/GetInvoice", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiInvoiceGetInvoiceGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of InvoiceContract</returns>
        public async System.Threading.Tasks.Task<InvoiceContract> ApiInvoiceGetInvoiceGetAsync ()
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<InvoiceContract> localVarResponse = await ApiInvoiceGetInvoiceGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (InvoiceContract)</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<InvoiceContract>> ApiInvoiceGetInvoiceGetAsyncWithHttpInfo ()
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            


            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<InvoiceContract>("/api/Invoice/GetInvoice", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiInvoiceGetInvoiceGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void ApiInvoiceGetPrintedInvoiceGet ()
        {
             ApiInvoiceGetPrintedInvoiceGetWithHttpInfo();
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse<Object> ApiInvoiceGetPrintedInvoiceGetWithHttpInfo ()
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var response = this.Client.Get<Object>("/api/Invoice/GetPrintedInvoice", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiInvoiceGetPrintedInvoiceGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiInvoiceGetPrintedInvoiceGetAsync ()
        {
             await ApiInvoiceGetPrintedInvoiceGetAsyncWithHttpInfo();

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<Object>> ApiInvoiceGetPrintedInvoiceGetAsyncWithHttpInfo ()
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            


            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<Object>("/api/Invoice/GetPrintedInvoice", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiInvoiceGetPrintedInvoiceGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
