/* 
 * Equimpent rental API V1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using bondora.homeAssignment.ApiClient.Client;
using bondora.homeAssignment.Models.Contracts.Cart;

namespace bondora.homeAssignment.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserCartApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>CartItemContract</returns>
        CartItemContract ApiUserCartCreatePost (long? productId = null, int? duration = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>ApiResponse of CartItemContract</returns>
        ApiResponse<CartItemContract> ApiUserCartCreatePostWithHttpInfo (long? productId = null, int? duration = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>long</returns>
        long ApiUserCartDeletePost (long? id = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>ApiResponse of long</returns>
        ApiResponse<long> ApiUserCartDeletePostWithHttpInfo (long? id = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>CartItemContract</returns>
        CartItemContract ApiUserCartGetGet (long? id = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>ApiResponse of CartItemContract</returns>
        ApiResponse<CartItemContract> ApiUserCartGetGetWithHttpInfo (long? id = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;CartItemContract&gt;</returns>
        List<CartItemContract> ApiUserCartListGet ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;CartItemContract&gt;</returns>
        ApiResponse<List<CartItemContract>> ApiUserCartListGetWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>CartItemContract</returns>
        CartItemContract ApiUserCartUpdatePost (long? id = null, int? duration = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>ApiResponse of CartItemContract</returns>
        ApiResponse<CartItemContract> ApiUserCartUpdatePostWithHttpInfo (long? id = null, int? duration = null);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserCartApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of CartItemContract</returns>
        System.Threading.Tasks.Task<CartItemContract> ApiUserCartCreatePostAsync (long? productId = null, int? duration = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of ApiResponse (CartItemContract)</returns>
        System.Threading.Tasks.Task<ApiResponse<CartItemContract>> ApiUserCartCreatePostAsyncWithHttpInfo (long? productId = null, int? duration = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of long</returns>
        System.Threading.Tasks.Task<long> ApiUserCartDeletePostAsync (long? id = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of ApiResponse (long)</returns>
        System.Threading.Tasks.Task<ApiResponse<long>> ApiUserCartDeletePostAsyncWithHttpInfo (long? id = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of CartItemContract</returns>
        System.Threading.Tasks.Task<CartItemContract> ApiUserCartGetGetAsync (long? id = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of ApiResponse (CartItemContract)</returns>
        System.Threading.Tasks.Task<ApiResponse<CartItemContract>> ApiUserCartGetGetAsyncWithHttpInfo (long? id = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;CartItemContract&gt;</returns>
        System.Threading.Tasks.Task<List<CartItemContract>> ApiUserCartListGetAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;CartItemContract&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CartItemContract>>> ApiUserCartListGetAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of CartItemContract</returns>
        System.Threading.Tasks.Task<CartItemContract> ApiUserCartUpdatePostAsync (long? id = null, int? duration = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of ApiResponse (CartItemContract)</returns>
        System.Threading.Tasks.Task<ApiResponse<CartItemContract>> ApiUserCartUpdatePostAsyncWithHttpInfo (long? id = null, int? duration = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserCartApi : IUserCartApiSync, IUserCartApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserCartApi : IUserCartApi
    {
        private bondora.homeAssignment.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserCartApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserCartApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserCartApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserCartApi(String basePath)
        {
            this.Configuration = bondora.homeAssignment.ApiClient.Client.Configuration.MergeConfigurations(
                bondora.homeAssignment.ApiClient.Client.GlobalConfiguration.Instance,
                new bondora.homeAssignment.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = bondora.homeAssignment.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserCartApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserCartApi(bondora.homeAssignment.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = bondora.homeAssignment.ApiClient.Client.Configuration.MergeConfigurations(
                bondora.homeAssignment.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new bondora.homeAssignment.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = bondora.homeAssignment.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PetApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UserCartApi(bondora.homeAssignment.ApiClient.Client.ISynchronousClient client,bondora.homeAssignment.ApiClient.Client.IAsynchronousClient asyncClient, bondora.homeAssignment.ApiClient.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = bondora.homeAssignment.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public bondora.homeAssignment.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public bondora.homeAssignment.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public bondora.homeAssignment.ApiClient.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public bondora.homeAssignment.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>CartItemContract</returns>
        public CartItemContract ApiUserCartCreatePost (long? productId = null, int? duration = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract> localVarResponse = ApiUserCartCreatePostWithHttpInfo(productId, duration);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>ApiResponse of CartItemContract</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse< CartItemContract > ApiUserCartCreatePostWithHttpInfo (long? productId = null, int? duration = null)
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (productId != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "ProductId", productId))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (duration != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "Duration", duration))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = this.Client.Post< CartItemContract >("/api/UserCart/Create", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartCreatePost", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of CartItemContract</returns>
        public async System.Threading.Tasks.Task<CartItemContract> ApiUserCartCreatePostAsync (long? productId = null, int? duration = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract> localVarResponse = await ApiUserCartCreatePostAsyncWithHttpInfo(productId, duration);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of ApiResponse (CartItemContract)</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract>> ApiUserCartCreatePostAsyncWithHttpInfo (long? productId = null, int? duration = null)
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (productId != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "ProductId", productId))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (duration != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "Duration", duration))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = await this.AsynchronousClient.PostAsync<CartItemContract>("/api/UserCart/Create", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartCreatePost", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>long</returns>
        public long ApiUserCartDeletePost (long? id = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<long> localVarResponse = ApiUserCartDeletePostWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>ApiResponse of long</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse< long > ApiUserCartDeletePostWithHttpInfo (long? id = null)
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (id != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "id", id))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = this.Client.Post< long >("/api/UserCart/Delete", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartDeletePost", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of long</returns>
        public async System.Threading.Tasks.Task<long> ApiUserCartDeletePostAsync (long? id = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<long> localVarResponse = await ApiUserCartDeletePostAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of ApiResponse (long)</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<long>> ApiUserCartDeletePostAsyncWithHttpInfo (long? id = null)
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (id != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "id", id))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = await this.AsynchronousClient.PostAsync<long>("/api/UserCart/Delete", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartDeletePost", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>CartItemContract</returns>
        public CartItemContract ApiUserCartGetGet (long? id = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract> localVarResponse = ApiUserCartGetGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>ApiResponse of CartItemContract</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse< CartItemContract > ApiUserCartGetGetWithHttpInfo (long? id = null)
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (id != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "id", id))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = this.Client.Get< CartItemContract >("/api/UserCart/Get", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartGetGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of CartItemContract</returns>
        public async System.Threading.Tasks.Task<CartItemContract> ApiUserCartGetGetAsync (long? id = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract> localVarResponse = await ApiUserCartGetGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <returns>Task of ApiResponse (CartItemContract)</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract>> ApiUserCartGetGetAsyncWithHttpInfo (long? id = null)
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (id != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "id", id))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<CartItemContract>("/api/UserCart/Get", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartGetGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;CartItemContract&gt;</returns>
        public List<CartItemContract> ApiUserCartListGet ()
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<List<CartItemContract>> localVarResponse = ApiUserCartListGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;CartItemContract&gt;</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse< List<CartItemContract> > ApiUserCartListGetWithHttpInfo ()
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var response = this.Client.Get< List<CartItemContract> >("/api/UserCart/List", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartListGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;CartItemContract&gt;</returns>
        public async System.Threading.Tasks.Task<List<CartItemContract>> ApiUserCartListGetAsync ()
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<List<CartItemContract>> localVarResponse = await ApiUserCartListGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;CartItemContract&gt;)</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<List<CartItemContract>>> ApiUserCartListGetAsyncWithHttpInfo ()
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            


            // make the HTTP request

            var response = await this.AsynchronousClient.GetAsync<List<CartItemContract>>("/api/UserCart/List", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartListGet", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>CartItemContract</returns>
        public CartItemContract ApiUserCartUpdatePost (long? id = null, int? duration = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract> localVarResponse = ApiUserCartUpdatePostWithHttpInfo(id, duration);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>ApiResponse of CartItemContract</returns>
        public bondora.homeAssignment.ApiClient.Client.ApiResponse< CartItemContract > ApiUserCartUpdatePostWithHttpInfo (long? id = null, int? duration = null)
        {
            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderContentType(@contentTypes);
            if (localVarContentType != null) requestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = bondora.homeAssignment.ApiClient.Client.ClientUtils.SelectHeaderAccept(@accepts);
            if (localVarAccept != null) requestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (id != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "Id", id))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (duration != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "Duration", duration))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = this.Client.Post< CartItemContract >("/api/UserCart/Update", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartUpdatePost", response);
                if (exception != null) throw exception;
            }

            return response;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of CartItemContract</returns>
        public async System.Threading.Tasks.Task<CartItemContract> ApiUserCartUpdatePostAsync (long? id = null, int? duration = null)
        {
             bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract> localVarResponse = await ApiUserCartUpdatePostAsyncWithHttpInfo(id, duration);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="bondora.homeAssignment.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"> (optional)</param>
        /// <param name="duration"> (optional)</param>
        /// <returns>Task of ApiResponse (CartItemContract)</returns>
        public async System.Threading.Tasks.Task<bondora.homeAssignment.ApiClient.Client.ApiResponse<CartItemContract>> ApiUserCartUpdatePostAsyncWithHttpInfo (long? id = null, int? duration = null)
        {

            bondora.homeAssignment.ApiClient.Client.RequestOptions requestOptions = new bondora.homeAssignment.ApiClient.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var contentType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", contentType);
            
            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);
            
            if (id != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "Id", id))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }
            if (duration != null)
            {
                foreach (var kvp in bondora.homeAssignment.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "Duration", duration))
                {
                    foreach (var value in kvp.Value)
                    {
                        requestOptions.QueryParameters.Add(kvp.Key, value);
                    }
                }
            }


            // make the HTTP request

            var response = await this.AsynchronousClient.PostAsync<CartItemContract>("/api/UserCart/Update", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("ApiUserCartUpdatePost", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
